### ISSUE TITLE
ERROR ON CART PAGE AND CHECKOUT PAGE

### ISSUE THREAD

**Issue by magsathaya** [vijayrami/Magelearn_Checkout#12]
I USE Magento 2.3 PHP 7.3
**ERROR ON CART PAGE AND CHECKOUT PAGE**         
I Think error on view/frontend/layout    xml files

**Comment by vijayrami** [comment]
It may be possible that Magento make changes in the layout xml files and there is something mismatch with the existing layout xml and this module's layout xml file.

You need to compare the xml files and resolved internally.
