### ISSUE TITLE
Issue on Cart Page Request Quote Button Click

### ISSUE THREAD

**Issue by mahendranmahi** [vijayrami/Magelearn_Checkout#13]
Am using the **Amasty Request a Quote** module. when am click a Request Quote Button Quote Page was Broken. Because of the Magelearn/Checkout/Plugin/Checkout/Model/DefaultConfigProvider.php file at line number **40**.
![image](https://user-images.githubusercontent.com/38282821/177851045-9fb26192-a1f6-4e61-b15a-df1f85c6bf99.png)

**Fix:-**
add **if($quoteItem){** at line 41
![image](https://user-images.githubusercontent.com/38282821/177851460-d8bb45d7-54e2-4651-9b07-187bc707d5f2.png)

**Comment by vijayrami** [comment]
Thanks for Raising an issue.

**Comment by vijayrami** [comment]
Code Updated !!
